# Generated by Django 5.1.4 on 2025-05-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_replacement_quantity', models.IntegerField()),
                ('replacement_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replacement_app.employee')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replacement_app.party')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replacement_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('complete_fitting', models.BooleanField(default=False)),
                ('driver_failure', models.BooleanField(default=False)),
                ('led_pcb_panel', models.BooleanField(default=False)),
                ('ip_failure', models.BooleanField(default=False)),
                ('glass_brackege', models.BooleanField(default=False)),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_details', to='replacement_app.productreplacement')),
            ],
        ),
    ]
